### PR TITLE
fix issue with On-Screen navigation buttons eclipsing the lower porti…

### PR DESCRIPTION
**Pull request by fahad86**
fix issue with On-Screen navigation buttons eclipsing the lower portion of the drawer when app installed with Ti SDK 6.1.0+

https://jira.appcelerator.org/browse/AC-5036

credits: Yordan Banev (Axway)

### CODE REVIEW

**Comment by viezel** [comment]
looks great, but we just merged this: https://github.com/viezel/NappDrawer/pull/203 
we cannot both have min 6.2.0 and 6.1.0 as minimum sdk.

@sgtcoolguy care to comment?

**Comment by fahad86** [comment]
thanks @viezel I've amended the my last commit (hence PR) to leave the min SDK and API values as is. The module was however compiled with 6.1.1.GA

**Comment by fahad86** [comment]
merge?

**Comment by viezel** [comment]
Thanks

**Pull request merged**
