### PR TITLE
tentative fixes for memory leaks (#86)

### PR DESCRIPTION
**Pull request by omorandi**
This PR contains a tentative solution for memory leak reported in #86. I quickly tested it in Instruments and it seems to work fine, but I didn't have time to test it with very complex cases.
Here's a summary of the changes: 
* MMDrawer files are ARC based, so I added the -fobjc-arc compiler flags for those.
* Removed the custom close() method from the drawer view, since it should be handled by the proxy.
* Added windowWillClose and windowDidClose methods for proper notification to the child window proxies.

### CODE REVIEW

**Comment by viezel** [comment]
working great. 
can you please bump the version, build the module with a zip in the dist and add a changelog? 

Thanks :+1:

**Comment by omorandi** [comment]
No problem. Done

**Comment by caspahouzer** [comment]
:+1:

**Comment by viezel** [comment]
sweet

**Comment by victsant** [comment]
Hi,

What is the command to clear the memory for the left drawer/center window. If i am using Alloy. 

I am trying to figure this out, but I'm stuck.

Thanks,
Victor

**Comment by victsant** [comment]
Hi,

I figure this out. 

Thanks,
Victor

**Comment by andersdp** [comment]
@victsant What did you figure out?

**Pull request merged**
