### PR TITLE
Burger To Arrow animation icon. (Android L style).

### PR DESCRIPTION
**Pull request by GeraudBourdin**
var drawer = NappDrawerModule.createDrawer({  
...
hamburgerIcon: true // set the burger icon
hamburgerIconColor:'#FFFFFF', // set the burger icon color
arrowAnimation :true // automatically set the hamburgerIcon and animate
it to arrow. (if set to true, no needs to set hamburgerIcon to true)
});

### CODE REVIEW

**Comment by guiled** [comment]
Nice :) :+1:

**Comment by caspahouzer** [comment]
Could we have this for iOS too?

**Comment by Anatidae-Project** [comment]
Love it.  I'd love it more if it were part of https://github.com/ricardoalcocer/actionbarextras
It seems possibly a better repo for it to live in.

**Comment by GeraudBourdin** [comment]
drawer needs to dialog with the animated icon to send the animation progress. So i don't think it would be efficient to add it to actionbar extra. that s why i made it for nappdrawer and  the tripvi ti.drawerlayout. Manumaticx have allready added it (and have helped adding  it to the ti.drawerlayout). Maybe i can send a patch to the actionbar extra but only for adding custom up icon (but without animation)?

**Comment by viezel** [comment]
WOW !! soo nice!

**Comment by GeraudBourdin** [comment]
There is a better padding value to set (sorry if i didn't sent another PR but i thought you weren't interested with this).

so, you could set 

    int paddingLeft  = (int) (12.25f * density);
    int paddingRight = (int) (12.25f * density);
(line 168, of the DrawerArrowDrawable.java).
to better reflect the android values.

Best regards.

**Comment by viezel** [comment]
Cool. Sorry at vacation, can you do another PR with that?

**Pull request merged**
