### PR TITLE
flagSecure + theme properties +  avoid addWindowToStack error

### PR DESCRIPTION
**Pull request by SquirrelMobile**
- Add Flagsecure (to prevent screenshot of the app)
- avoid addWindowToStack error
- Add possibility to change the Android theme of the drawer

### CODE REVIEW

**Comment by viezel** [comment]
HI @SquirrelMobile great stuff. I would be happy to merge it, but please dont delete old releases.

**Comment by SquirrelMobile** [comment]
@viezel i've add the old releases

**Comment by viezel** [comment]
can you please fix the conflicts?

**Comment by viezel** [comment]
@SquirrelMobile I would like to merge this, but cannot before the conflicts are resolved.

**Comment by iDalhaug** [comment]
Hi, I'm getting the addWindowToStack issue.. is there a release with the fix in?..

Thanks

**Pull request closed without merging**
